name: CI
on:
  push:
    branches: [ master ]
jobs:
  Test:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
    - name: core.symlinks
      run: git config --global core.symlinks true
    - name: Checkout
    - uses: actions/checkout@v2
      with:
          repository: WhisperingChaos/WindowsBatchScripts
    - name: Run Tests
      working-directory: .\file\reverse\test
      run: |
        chcp 850
        textFileReverse_test.cmd
