name: CI
on:
  push:
    branches: [ master ]
jobs:
  Test:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      working-directory: .\file\reverse\test
      run: |
        chcp 850
        del textFileReverse.cmd
        mklink textFileReverse.cmd ..\component\textFileReverse.cmd
        textFileReverse_test.cmd
