# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]

jobs:
  Test:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Run all test scripts
      working-directory: .\file\reverse\test
      run: textFileReverse_test.cmd

